### ISSUE TITLE
manage network connections on notebook

### ISSUE THREAD

**Issue by vlcinsky** [pydoit/doit-gallery#1]
# Annotation
As a user of my personal notebook I want to be able setting notebook
connectivity (wifi, mobile internet) up and down from command line as command
line is my most favourite UI.

# Tasks overview
List of base tasks:

    $ doit list
    available   List all available configured connections.
    status      List currently active network connections.
    up          Set given connection up (specific connection name required).
    down        Set given connection down.
    radio       Report status of network radio devices
    radioon     Set network radio device on
    radiooff    Set network radio device off.

and list incl. subtasks:

    $ doit list --all
    available       List all available configured connections.
    status          List currently active network connections.
    up              Set given connection up (specific connection name required).
    up:VPN
    up:home
    up:office
    up:hotspot
    up:train
    up:mobile
    down            Set given connection down.
    down:VPN
    down:home
    down:office
    down:hotspot
    down:train
    down:mobile
    radio           Report status of network radio devices
    radioon         Set network radio device on
    radioon:wifi
    radioon:wwan
    radiooff        Set network radio device off.
    radiooff:wifi
    radiooff:wwan

# Sample usage

When I travel by train and want to connect to (already preconfigured) train wifi:

    $ doit up:train
    .  up:train
    Connection succesfully activated (Active D-Bus path: /org/freedesktop/NetworkManager/ActiveConnection/1)

When in aeroplane, before take-off I switch all radio network devices:

    $ doit radiooff
    .  radiooff:wifi
    .  radiooff:wwan

When on the road and in need of mobile connectivity provided by LTE modem within my notebook:

    $ doit up:tm
    .  up:mobile
    Connection succesfully activated (Active D-Bus path: /org/freedesktop/NetworkManager/ActiveConnection/3)

# Users
- Number of users: 1
- Type of user: developer living on command line

# `doit` added value

Set of `nmcli` calls (e.g. `$ nmcli c up mobile`) packed into well named doit tasks, which are
easy to call and easy to list when one needs to remind how they are named.

# Meta

- Python: 3.6
- doit: 0.30.3
- OS: Ubuntu 16.04

# dodo file

- name of dodo file: `dodo.py`
- number of lines in dodo file: 82
- does it import tasks or actions from other files?: no
- url if you share the code publicly: Not sharing

# command and python package dependencies
Non-python based commands:
- nmcli (network manager CLI)

Python based commands:
- none

Other python packages:
- none

# `doit` features used

- [x] subtasks
- [ ] `"file_dep"` file dependency
- [ ] `"task_dep"`: task dependency
- [ ] `"clean"` clean task
    - [ ] custom clean action
- action types (anywhere, in `"actions"`, `"clean"`, `"uptodate"`...)
    - [ ] python-action
    - [x] cmd-action
- [ ] `"uptodate"` calculated uptodate
- [ ] `pathlib`
