### ISSUE TITLE
Sync data from deep dir tree to AWS S3

### ISSUE THREAD

**Issue by vlcinsky** [pydoit/doit-gallery#2]
# Annotation

As a application developer
I want to be able updating various files in deep directory tree to AWS S3 bucket
so that they can be used by our deployment tool.

As the tree is deep and files are in different depths, I want use the same procedure regardless of how deep in the tree I am currently working.

# Tasks overview

	$ doit list
	fetch      Fetch S3 updates to local filesystem.
	publish    Publish local updates to S3.
	syncdown   Fetch S3 updates to local filesystem incl. DELETION.
	syncup     Publish local updates to S3 and DELETE on S3 what is locally missing.

# Sample usage

Whan I have to clone my deployment configuration, I need to get all files from AWS S3 also present and in sync locally:

	$ git clone <url of deployment configuration project>
        $ cd deployment-config
        $ doit fetch

and all data from AWS S3 get downloaded to subdirectory aws-s3 where they belong.

When I need to update a file in the aws-s3 and publish the change to AWS S3:

	$ cd aws-s3/some/where/deep
	$ <update the file or two here>
	$ doit -k

As the default task is just `publish`, it runs the `publish` task.

The trick is to use `-k`, which stands for `--seek-file`, searching for `dodo.py` traversing up from current directories.

# Users
- Number of users: 2
- Type of user: administrators and developers of an application

# `doit` added value
The command to sync directories using `awscli` requires explicitly stated directory to start from and address to publish to AWS S3.

With `--seek-file`, user may forget about these complexities, as `doit` will colate the `dodo.py` (in project root) and from here call proper command.

# Meta
- Python: 3.6
- doit: 0.30.3
- OS: Ubuntu 16.04, Windows 10

# dodo file

- name of dodo file: `dodo.py`
- number of lines in dodo file: 33
- does it import tasks or actions from other files?: no
- url if you share the code publicly: Not sharing

# command and python package dependencies

Python based commands:
- awscli: aws (AWS CLI)

# `doit` features used

- [ ] subtasks
- [ ] `"file_dep"` file dependency
- [ ] `"task_dep"`: task dependency
- [ ] `"clean"` clean task
    - [ ] custom clean action
- action types (anywhere, in `"actions"`, `"clean"`, `"uptodate"`...)
    - [ ] python-action
    - [x] cmd-action
- [ ] `"uptodate"` calculated uptodate
- [ ] `pathlib`
