### ISSUE TITLE
Backup and purge obsolete records from database

### ISSUE THREAD

**Issue by vlcinsky** [pydoit/doit-gallery#3]
# Annotation
As a system administrator,
I want to be able purging database, used by other services, make sure the
services are stopped and started when needed, and publish compressed backup to
AWS S3
to perform these interconnected activities safely and as quickly as possible to shorten downtime.

# Tasks overview

List of base tasks:

    $ doit list
    compress         Compress backup of database file
    copy2s3          Move archived database to AWS S3 bucket
    purgedb          Purge database file
    start_services   Start related services
    stop_services    Stop related services

Subtasks are used (there used to be more databases):

    doit list --all
    compress                 Compress backup of database file
    compress:data2.db         
    copy2s3                  Move archived database to AWS S3 bucket
    copy2s3:data2.db          
    purgedb                  Purge database file
    purgedb:data2.db          
    start_services           Start related services
    start_services:data2.db   
    stop_services            Stop related services
    stop_services:data2.db    

# Sample usage

There are two default tasks: "copy2s3", which indirectly (via dependencies) cause purging, and
"start_service", which ensure, we start stopped services after all is done.

Starting `doit` invokes these two default tasks:

    $ doit
    .  stop_services:data2.db
    DataDelta2: stopped
    createSnapshot2: stopped
    .  purgedb:data2.db
    Count delta messages:|17252
    Count unique msg ids:|7881
    ===Backup the database===
    2017-10-01 21:07:16|Delete expired messages, incl. older versions
    Count delta messages:|3701
    Count unique msg ids:|1795
    2017-10-01 21:07:17|Delete obsolete delta messages
    Count delta messages:|2631
    Count unique msg ids:|1795
    2017-10-01 21:07:17|Purge not referenced documents
    Count document (before):|12917
    Count document (after ):|2091
    2017-10-01 21:07:17|Commit the changes
    2017-10-01 21:07:18|Vacuum the database
    2017-10-01 21:07:18|Now WE ARE DONE
    !!!!! consider calling $ doit start_services!!!!
    .  compress:data2.db

    7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
    .....
    Creating archive data2.db.7z

    Compressing  data2.db.backup

    Everything is Ok
    .  copy2s3:data2.db
    upload: ./data2.db.7z to s3://buck.et/some/where/data2.db-2017-10-01T21_07_18.7z
    2017-10-01 21:07:29    3472150 data2.db-2017-10-01T21_07_18.7z
    !!!Consider `$ doit clean -a`!!! to complete the work
    .  start_services:data2.db
    DataDelta2: started
    createSnapshot2: started

Finally, when all is done incl. publishing file to S3, we can clean our local directory:

    $ doit clean -a
    purgedb:data2.db - removing file 'data2.db.backup'
    compress:data2.db - removing file 'data2.db.7z'

# Users
- Number of users: 1
- Type of user: system administrator

# `doit` added value
Particular tasks are defined in simple manner and via dependencies they get
orchestrated properly.

The tasks are automated thus the time related services are stopped is very short.

With simple README.rst file, the action can be delegated to another person.

# Meta

- Python: 2.7
- doit: 0.28.0
- OS: Ubuntu 14.04.5 LTS

# dodo file

- name of dodo file: `dodo.py`
- number of lines in dodo file: 119
- does it import tasks or actions from other files?: no
- url if you share the code publicly: not sharing

# command and python package dependencies

Non-python based commands:
- echo
- sudo
- 7z (compression)
- sqlite3 (manage sqlite database)

Python based commands:
- supervisord: supervisorctl (service manager)
- awscli: aws (interact with AWS)

# `doit` features used

- [x] subtasks
- [x] `"file_dep"` file dependency
- [ ] `"task_dep"`: task dependency
- [x] `"clean"` clean task
    - [ ] custom clean action
- action types (anywhere, in `"actions"`, `"clean"`, `"uptodate"`...)
    - [ ] python-action
    - [x] cmd-action
- [x] `"uptodate"` calculated uptodate
- [ ] `pathlib`
